### ISSUE TITLE
Support in Mac systems 

### ISSUE THREAD

**Issue by rkoystart** [levyfan/sentencepiece-jni#22]
Hi @levyfan would like to whether this sentence piece works in a Mac systems

**Comment by levyfan** [comment]
you can have a try

**Comment by rkoystart** [comment]
@levyfan I will be able to generate the sentencepiece wrapper jar in the Mac systems using the same commands mentioned in the README.md right ?

**Comment by levyfan** [comment]
I haven't tested on Mac. You could figure it out by yourself.
