### ISSUE TITLE
Same model and same input, But getting different output in Linux (Ubuntu) and Windows.

### ISSUE THREAD

**Issue by heflinstephenraj** [levyfan/sentencepiece-jni#25]
Hello there,
I have cloned https://github.com/levyfan/sentencepiece-jni/releases/tag/v0.0.1 and built it on Ubuntu and windows.
Then I tested both jars with the same input and same model. 
Surprisingly I am getting different results for the same input and same model. 

The input sentences is  `Necesita más discusiones`
Output on linux jar: ` [▁, Necesita, ▁más, ▁disc, us, iones]`
Output on windows jar: `[?, Necesita, ?m, �, �, s, ?disc, us, iones]`
Python output: `['▁', 'Necesita', '▁más', '▁disc', 'us', 'iones']`

I noticed, If I pass non-diacritics sentence, Both windows jar and linux jar are producing the same result 
The input sentences: `Luego`
Output on Linux jar: `[▁Luego]`
Output on windows jar: `[?Luego]`
Python output: `['▁Luego']`

### Java code snippet 
```
import com.github.google.sentencepiece.SentencePieceProcessor;

public class Main {

    public static void main(String[] args)  throws InterruptedException{
    SentencePieceProcessor ss = new SentencePieceProcessor();
    ss.load("tokenizer.model");
    System.out.println(ss.encodeAsPieces("Necesita más discusiones"));

    }
}
```

I am using [hugging face model](https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2) 
You can use this model in python to cross-check the result
```
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained('sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2')
print(tokenizer.tokenize("Luego"))
```

For your reference, I have attached those two jars and the model below
[Windows jar](https://drive.google.com/file/d/1YpRyhQaztcX6veB0qvO-Ab1zWGhRx7xK/view?usp=sharing) 
[Ubuntu](https://drive.google.com/file/d/11yUnZWZHQW-_Uz71tdhvsgcr-XtvqxG1/view?usp=sharing)
[Model](https://drive.google.com/file/d/14BvUro-NfkNI0T9N6FhDop4azNaV3Zp4/view?usp=sharing)

Please help out @levyfan  @erip

**Comment by erip** [comment]
This looks like an encoding issue and not an issue with sentencepiece or sentencepiece-jni. What happens when run `System.out.println(ss.encodeAsIds("Necesita más discusiones"));` on both platforms?

**Comment by heflinstephenraj** [comment]
I have tested it on two different windows machines. Surprisingly I am getting two different outputs for the same model, the same jar, and the same input.

I have attached the two system information for your reference.  @erip 

Machine 1 
![image](https://user-images.githubusercontent.com/51231149/183251019-cd9cee5e-07a1-4092-b6f0-b5a31cd54ea9.png)

Input text: `Necesita más discusiones`
Output: `['▁', 'Necesita', '▁más', '▁disc', 'us', 'iones']`

Machine 2 
<img width="1512" alt="Screenshot 2022-08-05 at 5 49 23 PM" src="https://user-images.githubusercontent.com/51231149/183250902-01043a1d-fe5c-4eb7-a674-4eae0d09f085.png">
Input text: `Necesita más discusiones`
Output: `[?, Necesita, ?m, �, �, s, ?disc, us, iones]`

**Comment by erip** [comment]
Can you try the thing I recommended in the last comment? It would be helpful to see if the IDs match.

**Comment by heflinstephenraj** [comment]
Sure, I will try that and update you. 
Thank you for your response.

**Comment by heflinstephenraj** [comment]
```
import com.github.google.sentencepiece.SentencePieceProcessor;
import  java.util.*;

public class Main {

    public static void main(String[] args)  throws InterruptedException{
        SentencePieceProcessor ss = new SentencePieceProcessor();
        ss.load("tokenizer.model");
        System.out.println( convertToArray(ss.encodeAsIds( "Necesita más discusiones")) );
        System.out.println(convertToArray(ss.encodeAsIds("Luego")) );
    }
    public static ArrayList<Integer> convertToArray(int[] input){
        ArrayList<Integer> result = new ArrayList<>();
        for(int i =0; i<input.length;i++)
            result.add(input[i]);
        return result;
    }
}
```
I ran the above Java code on two different windows machines. Surprisingly I am getting two different outputs.

Machine 1:
```
[5, 225102, 1004, 17115, 222, 55104]
[147499]
```
Machine 2:
```
[5, 225102, 346, 7491, 55948, 6, 17115, 222, 55104]
[147499]
```
I have attached the machine configurations in my previous comment for your reference.
Please help out @erip @levyfan

**Comment by erip** [comment]
Thanks for that. What we can conclude from this is:

1. The underscore character indicating space is not rendered on Windows but is correctly handled under the hood.
2. There is some inconsistency between Windows and non-Windows (discusiones is split differently)

I can try to debug this soon but admittedly I'm a bit busy currently so it may take a bit of time.

**Comment by heflinstephenraj** [comment]
I have checked in python on the windows machine (machine 2 - mentioned above) and ubuntu machine. It is producing the same result.  @erip 
Thank you @erip

**Comment by erip** [comment]
Thanks, this narrows down the search space a lot. I'll try to look at this ASAP.

**Comment by heflinstephenraj** [comment]
I am using pre-trained model from hugging face. 
For info about the tokenizer, please visit https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2

**Comment by erip** [comment]
Great, that's very helpful for debugging. More info forthcoming.

**Comment by heflinstephenraj** [comment]
Thank you @erip

**Comment by rkoystart** [comment]
Hi @erip , while going through the native code in this repo, just wanted to know whether the error is because of the repo code or the sentencepiece code itself.
Tried adding the following code
```
for (int i = 0; i < ids.size(); i++)
      std::cout << "the token is: " << ids.at(i);
```
after the [line1](https://github.com/levyfan/sentencepiece-jni/blob/23ee83c0e4c86bbd35b46937d2245a68e7e6e0f5/src/main/native/com_github_google_sentencepiece_SentencePieceJNI.cc#L254) and [line2](https://github.com/levyfan/sentencepiece-jni/blob/23ee83c0e4c86bbd35b46937d2245a68e7e6e0f5/src/main/native/com_github_google_sentencepiece_SentencePieceJNI.cc#L277) for encodeaspieces and encodeasids functions.

Created a windows jar for java and executed the java jar in windows server (same specs as mentioned by @heflinstephenraj ).
And got the following output in windows server (errored output):
` the token is: 5 the token is: 225102 the token is: 346 the token is: 7491 the token is: 55948 the token is: 6 the token is: 17115 the token is: 222 the token is: 55104`

And got the following output in windows 10 (Correct output):
`the token is: 5 the token is: 225102 the token is: 1004 the token is: 17115 the token is: 222 the token is: 55104`

**Comment by erip** [comment]
It seems likely that it's an error in this repo rather than sentencepiece upstream (since spm seems to generate identical IDs on the two platforms). @rkoystart can you confirm whether those outputs match with native spm on Windows server and Win10? That can help us confirm whether it's a Java issue for an spm issue (though I think it's a java issue).

**Comment by rkoystart** [comment]
> can you confirm whether those outputs match with native spm on Windows server and Win10? 

Hi @erip can you elaborate more on how this needs to be done

**Comment by erip** [comment]
Use the python sentencepiece API to encode the same sentence to IDs. Confirm that the IDs are the same.

**Comment by rkoystart** [comment]
@erip sure. Will do it and post it here

**Comment by rkoystart** [comment]
The output using python library in Windows Server Machine:

![Screenshot from 2022-08-11 11-05-13](https://user-images.githubusercontent.com/64691602/184070512-e792dca8-b395-4da9-a982-b2f6af07c89c.png)

The output Using the python library in Windows 10 Machine:

![Screenshot from 2022-08-11 11-04-53](https://user-images.githubusercontent.com/64691602/184070962-ab4465fd-b0c5-4a5d-a604-1c6014ed674e.png)

@erip The output remains the same in both the machines while using the python library

**Comment by levyfan** [comment]
I guess this might be caused by windows default encoding, https://javarevisited.blogspot.com/2012/01/get-set-default-character-encoding.html#axzz7be2RcQZN

**Comment by erip** [comment]
The default encoding impacts the rendering but not the underlying storage. This looks like a bug in the JNI since the python library generates identical tokenizations under the same model on different platforms but the Java code does not.

**Comment by levyfan** [comment]
> The default encoding impacts the rendering but not the underlying storage. This looks like a bug in the JNI since the python library generates identical tokenizations under the same model on different platforms but the Java code does not.

Can we add a windows server 2016 CI on github? This might help reproduce the bug.

**Comment by erip** [comment]
> Can we add a windows server 2016 CI on github? This might help reproduce the bug.

[Unfortunately not.](https://github.blog/changelog/2021-10-19-github-actions-the-windows-2016-runner-image-will-be-removed-from-github-hosted-runners-on-march-15-2022/)

**Comment by rkoystart** [comment]
@levyfan will check whether it is an encoding issue and post it here.

**Comment by heflinstephenraj** [comment]
After changing the encoding to UTF-8, the tokenizer is able to produce the correct token ids.
