### ISSUE TITLE
Is it possible to use this on Android device?

### ISSUE THREAD

**Issue by gitathrun** [levyfan/sentencepiece-jni#3]
Hi, I am wandering if this JNI could be used on Android device and any example of the process?

Great work, thank you.

**Comment by levyfan** [comment]
Hi, I haven't tested it against Android. The project only depend on JNI (and sentencepiece). So I suppose it would work on Android.

You might need to check the c++ compiling at https://github.com/levyfan/sentencepiece-jni/blob/master/src/main/native/CMakeLists.txt and also the dynamic library loading at https://github.com/levyfan/sentencepiece-jni/blob/master/src/main/java/com/github/google/sentencepiece/NativeLibLoader.java

**Comment by gitathrun** [comment]
Thanks for the tip, I will try to run it on Android.

I will update if there is any progress.

**Comment by gitathrun** [comment]
@levyfan Not quit understand why we need NativeLibLoader.java, I understand it fetch the absolute path of the library and copy the content of the JNI into a temp file, for the system.load().

But why we need that process? Any idea we need those additional steps?

**Comment by levyfan** [comment]
Because you can not directly load a dynamic library inside JAR. You should first copy the .so file out to a directory, and then load it.

**Comment by gitathrun** [comment]
How about the static library? If we use the .a instead of .so, is it going to work? I managed to use static library for sentencepiece C++ program, and trying to convert it with JNI.

**Comment by levyfan** [comment]
For loading inside JAR? No, that is not possible. You can regard JAR as zip file. I think you should use NDK to directly produce APK rather than JAR. In that way, you do not need NativeLibLoader.java.

**Comment by levyfan** [comment]
The difference between Android and Oracle `System.loadLibrary` is that: Android will search and load library inside APK, but Oracle won't do that inside JAR.

https://stackoverflow.com/questions/4113317/load-library-from-jar

**Comment by gitathrun** [comment]
Great information, thanks! Another thing I am worry about is the pthreads library, it is required in linking libraries, but according to Android developers it is supported in NDK but not allows developer to link it in cli, I will update if I got anything.

**Comment by gitathrun** [comment]
As described here: https://developer.android.com/ndk/guides/stable_apis.html#c_library
**Note that on Android, unlike Linux, there are no separate libpthread or librt libraries. That functionality is included directly in libc, which does not need to be explicitly linked against.**

For Linux development, without the -lpthread in the linking stage, build process still success, but when executing the program,  the protobuf-lite throws error due to the missing of pthread library.

```
[libprotobuf FATAL xxxxxxx/protobuf-lite/generated_message_util.cc:801] CHECK failed: (scc->visit_status.load(std::memory_order_relaxed)) == (SCCInfoBase::kRunning): 
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: (scc->visit_status.load(std::memory_order_relaxed)) == (SCCInfoBase::kRunning): 
Aborted (core dumped)
```

So, I think the challenge here for Android development is how to make sure the pthread is properly integrated when it re-positioned into libc in NDK.

**Comment by levyfan** [comment]
Is that error related to pthread? Maybe you could ask https://github.com/google/sentencepiece to help you build their libs on Android.

Our build is as simple as a `ExternalProject_Add` and everything depends on building sentencepiece itself.

**Comment by gitathrun** [comment]
I am able to get SentencePiece work (only model file load and encode fucntion at the moment) on Android device, it does not require hard link for pthread library, since the android ndk toolchain will automatic link the pthread library.

But there is an issue about load the model file, which is fetching absolute path from Android device, rather than use an URI or AssetsManger from the Android App. Here is my question:

For the function in native code:
```
JNIEXPORT void JNICALL Java_com_github_google_sentencepiece_SentencePieceJNI_sppLoad
        (JNIEnv *env, jclass cls, jlong ptr, jstring filename) {
    auto* spp = (SentencePieceProcessor*) ptr;

    jsize len = env->GetStringUTFLength(filename);

    const char* str = env->GetStringUTFChars(filename, nullptr);
    Status status = spp->Load(min_string_view(str, len));
    env->ReleaseStringUTFChars(filename, str);

    throwStatus(env, status);
}
```

The **str** and **len** in the statement
```
    Status status = spp->Load(min_string_view(str, len));
```

does it stands for memory pointer and length when model is positioned in memory?

**Comment by levyfan** [comment]
`str` and `len` is the file name (and the path) of the model, eg, `/home/abc/xxx.spm`. It is not the file content.

If you first load the file content by Java, then you should use `sppLoadFromSerializedProto` to build the model.

**Comment by gitathrun** [comment]
Well, that is problem in Android, since Android (and iOS) do not encourange developers to use the absolute path in app, and I am looking for the solution.

**Comment by levyfan** [comment]
It is not about c++ stream or Java InputStream.

First, load the file content to a byte[] by one of your favorite methods, for example, AssetManager

```
InputStream is = AssetManager.open("your_model_path");

// readAllBytesFromInputStream is whatever code reads all bytes from the input stream
// for example use a ByteArrayOutputStream as the buffer
byte[] content = readAllBytesFromInputStream(is);
```

Then, use `sp.loadFromSerializedProto` to load the sentence piece object

```
sp.loadFromSerializedProto(content);
```

**Comment by gitathrun** [comment]
All right, I got your point, I will try this one.

**Comment by gitathrun** [comment]
@levyfan Yeah, your solution does work, now it is able to load the model file from Assets directory. It seems in Android development, it is better to load the file and convert to byte array through **MappedByteBuffer** class, rather than direct fetch byte[] from InputStream, otherwise it cause an error point to 

```
sentencepiece_processor.cc:73
model_proto->ParseFromArray(serialized.data(), serialized.size()));
```

**Comment by jhw1130** [comment]
@gitathrun 

Hi, I'm trying to run this JNI on Android and currently have many problems.
I tried to modify the CMakeLists.txt file to sync gradle successfully.
But this doesn't seem to work.
Could you please provide a simple guide for running this JNI on Android?

**Comment by drc10723** [comment]
@gitathrun I am trying to use sentence piece for the android app. Do you have any documentation on the required steps and issues faced for the same?

**Comment by gitathrun** [comment]
@drc10723 Some steps for building the ARM library in [here](https://github.com/google/sentencepiece/issues/346#issuecomment-653247076)

**Comment by Arman-IMRSV** [comment]
@gitathrun I am trying to use sentencepiece in an android app as well. Would you be able to share the combiled library files please?
