### ISSUE TITLE
Issues for the file 'sentencepiece/src/sentencepiece-build/src/libsentencepiece.a'

### ISSUE THREAD

**Issue by QIANQIAN201** [levyfan/sentencepiece-jni#6]
Hello,
Firstly thank you for your great work.
When i want to implement your sentencepiece JNI in Android studio, i have this error: ninja: error: 'sentencepiece/src/sentencepiece-build/src/libsentencepiece.a' is needed to build libsentencepiece.so . 

It seems like that i need to add the file 'libsentencepiece.a'. Therefore could you please tell me how to get this file? I suppose that i should use the command 'g++ -c hello.cc' to obtain 'hello.o' then use 'ar cr libsentencepiece.a hello.o' to obtain  'libsentencepiece.a'. But i don't kown the 'hello.cc' correspond which code.cc in the github[ sentencepiece/google](https://github.com/google/sentencepiece/tree/master/src)

Thanks a lot for your reply!

**Comment by levyfan** [comment]
'libsentencepiece.a' is built by https://github.com/levyfan/sentencepiece-jni/blob/master/src/main/native/CMakeLists.txt ExternalProject_Add, and cmake is invoked by https://github.com/levyfan/sentencepiece-jni/blob/master/pom.xml exec-maven-plugin.

**Comment by levyfan** [comment]
You could manually invoke cmake for Android/ARM build by https://github.com/google/sentencepiece/issues/346#issuecomment-653247076

**Comment by QIANQIAN201** [comment]
Thanks a lot for your explain and showing me the useful comment!
Wish you good luck for your next project.
