### ISSUE TITLE
 How to use sentencepiece in java

### ISSUE THREAD

**Issue by duanzhenke** [levyfan/sentencepiece-jni#9]
How to use sentencepiece in java，
Is there any maven dependency？

Thanks a lot!!

**Comment by levyfan** [comment]
The project does not upload jar to maven central as it contains native code. You should build and install it by `mvn clean install` and include it in another project by
```
    <groupId>com.github.levyfan</groupId>
    <artifactId>sentencepiece</artifactId>
    <version>0.0.1-SNAPSHOT</version>
```
